#!/bin/bash

echo "manual" > /sys/class/drm/card0/device/power_dpm_force_performance_level
echo "s 1 1900" > /sys/class/drm/card0/device/pp_od_clk_voltage
echo "vc 2 1900 998" > /sys/class/drm/card0/device/pp_od_clk_voltage
echo "m 1 900" > /sys/class/drm/card0/device/pp_od_clk_voltage
echo "c" > /sys/class/drm/card0/device/pp_od_clk_voltage
