#!/bin/sh

meson setup _build_x64 \
       -D c_args="-march=native -O3"  \
       -D c_link_args="-march=native -O3" \
       -D cpp_args="-march=native -O3" \
       -D cpp_link_args="-march=native -O3" \
       -D b_ndebug=true \
       -D b_lto=true \
       -D buildtype=release \
       -D prefix="/opt/mesa-git" \
       -D platforms=x11,wayland \
       -D dri-drivers="[]" \
       -D dri3=enabled \
       -D egl=enabled \
       -D shader-cache=true \
       -D gallium-drivers=radeonsi,swrast \
       -D vulkan-drivers=amd,swrast \
       -D swr-arches=avx,avx2 \
       -D gallium-nine=true \
       -D llvm=enabled \
       -D lmsensors=enabled \
       -D osmesa=true \
       -D shared-glapi=enabled \
       -D glx=dri \
       -D option=true


ninja -C _build_x64 install

export CC="gcc -m32" 
export CXX="g++ -m32" 
export PKG_CONFIG=/usr/bin/i686-pc-linux-gnu-pkg-config

meson setup _build_x86 \
	--native-file llvm32.native \
       -D c_args="-march=native -O3"  \
       -D c_link_args="-march=native -O3" \
       -D cpp_args="-march=native -O3" \
       -D cpp_link_args="-march=native -O3" \
       -D b_ndebug=true \
       -D b_lto=true \
       -D buildtype=release \
       -D prefix="/opt/mesa-git" \
       --libdir="/opt/mesa-git/lib32"\
       -D platforms=x11,wayland \
       -D dri-drivers="[]" \
       -D dri3=enabled \
       -D egl=enabled \
       -D shader-cache=true \
       -D gallium-drivers=radeonsi,swrast \
       -D vulkan-drivers=amd,swrast \
       -D swr-arches=avx,avx2 \
       -D gallium-nine=true \
       -D llvm=enabled \
       -D lmsensors=enabled \
       -D osmesa=true \
       -D shared-glapi=enabled \
       -D glx=dri \
       -D option=true

ninja -C _build_x86 install%
