#!/bin/sh

meson setup build \
       -D c_args="-march=native -O3"  \
       -D c_link_args="-march=native -O3" \
       -D cpp_args="-march=native -O3" \
       -D cpp_link_args="-march=native -O3" \
       -D b_ndebug=true \
       -D b_lto=true \
       -D buildtype=release \
       -D prefix="$HOME/.local/share/mesa-git" \
       -D platforms=x11,wayland \
       -D dri-drivers="[]" \
       -D shader-cache=true \
       -D gallium-drivers=radeonsi,swrast,zink \
       -D vulkan-drivers=amd \
       -D gallium-nine=true \
       -D vulkan-device-select-layer=true \
       -D vulkan-overlay-layer=true \
       -D gles1=false \
       -D gles2=false

ninja -C _build

ninja -C _build install